# Generated by Django 3.1 on 2022-09-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
